### ISSUE TITLE
Velocity support

### ISSUE THREAD

**Issue by angwdev** [Phoenix616/GlobalWarps#1]
#### Is your feature request related to a problem? Please describe.

No

#### Describe the solution you'd like

Velocity support

#### Additional context

`com.velocitypowered.api.plugin.InvalidPluginException: The plugin file GlobalWarps.jar appears to be a Bukkit or BungeeCord plugin.`

**Comment by Phoenix616** [comment]
I'm very open for anything Velocity but I unfortunately can't really give any ETA on this :S

**Comment by angwdev** [comment]
Good to know

**Comment by Phoenix616** [comment]
Supported since cd69e03e3fe3786ebf394b1365c2cec59a52db3f Forgot there was an issue for that ^^'
